language: csharp
solution: CSharpStaticAnalyzer.sln
mono:
 - beta
script:
 - xbuild /p:Configuration=Release CSharpStaticAnalyzer.sln
 - mono CSharpStaticAnalyzer/bin/Release/CSharpStaticAnalyzer.exe TestSources/Test1.cs